services:
  healthcheck:
    build: .
    image: lovekush1702/healthcheck-app:${IMAGE_TAG:-latest}
    container_name: healthcheck
    ports:
      - "80:4000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
